NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"

[[CURRENCIES]]
code = "BLNT"
issuer = "GASEXARQMF4HVX3TPIKN2UNV5UCMT7TSXTESJSMN67R46GNXLJN4EWR6"
display_decimals = 7
name = "Blend Token"
desc = "Testnet BLNT used by Blend V2.1"
image = "https://blnd.trade/icons/tokens/blnd-yellow.svg"
